#!/usr/bin/env bash
# Opt-in real OMP /exit acknowledgement on a guarded non-default Herdr lab.
set -u

if [ "${FM_OMP_HERDR_EXIT_LIVE_E2E:-0}" != 1 ]; then
  echo "skip: set FM_OMP_HERDR_EXIT_LIVE_E2E=1 to run the isolated OMP Herdr exit lifecycle"
  exit 0
fi

# shellcheck source=tests/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

command -v omp >/dev/null 2>&1 || fail "omp not found"
command -v herdr >/dev/null 2>&1 || fail "herdr not found"
command -v jq >/dev/null 2>&1 || fail "jq not found"

OMP_BIN=$("$ROOT/bin/fm-omp-capabilities.sh" --print-binary) || fail "OMP capability check failed"
HERDR_LAB_HELPER=${HERDR_LAB_HELPER:-$ROOT/bin/fm-herdr-lab.sh}
[ -x "$HERDR_LAB_HELPER" ] || fail "Herdr lab helper is not executable: $HERDR_LAB_HELPER"

LAB=$(fm_test_tmproot fm-omp-herdr-exit-live)
SESSION="fm-lab-omp-exit-$$-${RANDOM:-0}"
PROJECT="$LAB/project"
SESSION_DIR="$LAB/omp-sessions"
WRAPPER_BIN="$LAB/bin"
WRAPPER_LOG="$LAB/herdr-wrapper.log"
OMP_EXTENSION="$LAB/fm-crew-omp.ts"
OMP_READY="$LAB/omp-ready"
OMP_STARTED="$LAB/omp-started"
OMP_TURN_ENDED="$LAB/omp-turn-ended"
BASE_PATH=$PATH
TEARDOWN_DONE=0

cleanup() {
  if [ "${FM_OMP_HERDR_KEEP_FAILED:-0}" = 1 ] && [ "$TEARDOWN_DONE" -ne 1 ]; then
    echo "diagnostic: preserving failed lab $SESSION at $LAB" >&2
    return
  fi
  if [ "$TEARDOWN_DONE" -ne 1 ]; then
    PATH="$BASE_PATH" "$HERDR_LAB_HELPER" teardown "$SESSION" >/dev/null 2>&1 || true
  fi
  rm -rf "$LAB"
}
trap cleanup EXIT

mkdir -p "$PROJECT" "$SESSION_DIR" "$WRAPPER_BIN"
printf 'fixture\n' > "$PROJECT/README.md"
git init -q -b main "$PROJECT"
fm_git_identity fmtest fmtest@example.invalid
git -C "$PROJECT" add README.md
git -C "$PROJECT" commit -qm init

PATH="$BASE_PATH" "$HERDR_LAB_HELPER" provision "$SESSION" >/dev/null \
  || fail "could not provision the isolated Herdr lab"

cat > "$WRAPPER_BIN/herdr" <<SH
#!/usr/bin/env bash
set -u
session='$SESSION'
helper='$HERDR_LAB_HELPER'
base_path='$BASE_PATH'
log='$WRAPPER_LOG'
printf '%q ' "\$@" >> "\$log"
printf '\n' >> "\$log"
argc=\$#
[ "\$argc" -ge 2 ] || { echo "test wrapper refused a Herdr command without explicit session binding" >&2; exit 96; }
args=("\$@")
penultimate=\${args[\$((argc - 2))]}
last=\${args[\$((argc - 1))]}
[ "\$penultimate" = --session ] && [ "\$last" = "\$session" ] \
  || { echo "test wrapper refused a Herdr command without the exact lab session" >&2; exit 96; }
set -- "\${args[@]:0:\$((argc - 2))}"
case "\${1:-}" in
  server|session)
    echo "test wrapper refused an unguarded Herdr lifecycle command" >&2
    exit 97
    ;;
esac
exec env PATH="\$base_path" "\$helper" run "\$session" "\$@"
SH
chmod +x "$WRAPPER_BIN/herdr"

cat > "$OMP_EXTENSION" <<TS
// Matches the OMP worker/scout extension generated by bin/fm-spawn.sh.
import { execFile } from "node:child_process";
export default function (omp: any) {
  omp.on("session_start", () => execFile("touch", ["$OMP_READY"]));
  omp.on("turn_start", () => execFile("touch", ["$OMP_STARTED"]));
  omp.on("turn_end", () => execFile("touch", ["$OMP_TURN_ENDED"]));
}
TS

create=$(PATH="$BASE_PATH" "$HERDR_LAB_HELPER" run "$SESSION" \
  workspace create --cwd "$PROJECT" --label omp-exit-live --no-focus) \
  || fail "could not create the guarded OMP workspace"
PANE=$(printf '%s' "$create" | jq -r '.result.root_pane.pane_id // empty')
[ -n "$PANE" ] || fail "Herdr workspace creation returned no root pane"
TARGET="$SESSION:$PANE"

printf -v launch \
  "exec env OMP_SKIP_SETUP=1 PATH=%q %q --model openai-codex/gpt-5.6-sol --thinking low --session-dir %q --auto-approve -e %q %q" \
  "$WRAPPER_BIN:$BASE_PATH" "$OMP_BIN" "$SESSION_DIR" "$OMP_EXTENSION" "Reply exactly OMP_HERDR_EXIT_READY."
PATH="$BASE_PATH" "$HERDR_LAB_HELPER" run "$SESSION" pane run "$PANE" "$launch" >/dev/null \
  || fail "could not launch OMP in the guarded Herdr pane"

agent=
SESSION_FILE=
for _ in $(seq 1 600); do
  agent=$(PATH="$BASE_PATH" "$HERDR_LAB_HELPER" run "$SESSION" agent get "$PANE" 2>/dev/null || true)
  identity=$(printf '%s' "$agent" | jq -r '.result.agent.agent // empty' 2>/dev/null)
  status=$(printf '%s' "$agent" | jq -r '.result.agent.agent_status // empty' 2>/dev/null)
  SESSION_FILE=$(printf '%s' "$agent" | jq -r 'select(.result.agent.agent_session.kind == "path") | .result.agent.agent_session.value // empty' 2>/dev/null)
  if [ "$identity" = omp ] && { [ "$status" = idle ] || [ "$status" = "done" ]; } \
    && [ -n "$SESSION_FILE" ] && [ -f "$OMP_READY" ] && [ -f "$OMP_STARTED" ] && [ -f "$OMP_TURN_ENDED" ]; then
    break
  fi
  sleep 0.25
done
[ "${identity:-}" = omp ] || fail "Herdr never reported the exact native OMP identity"
case "${status:-}" in idle|done) ;; *) fail "OMP did not become safely idle before /exit (status=${status:-unknown})" ;; esac
if [ ! -f "$OMP_READY" ] || [ ! -f "$OMP_STARTED" ] || [ ! -f "$OMP_TURN_ENDED" ]; then
  fail "the generated OMP extension missed lifecycle acknowledgement (ready=$([ -f "$OMP_READY" ] && echo yes || echo no), started=$([ -f "$OMP_STARTED" ] && echo yes || echo no), ended=$([ -f "$OMP_TURN_ENDED" ] && echo yes || echo no))"
fi
case "$SESSION_FILE" in
  "$SESSION_DIR"/*.jsonl) ;;
  *)
    shape=$(printf '%s' "$agent" | jq -c '.result.agent | {agent,agent_status,agent_session}' 2>/dev/null)
    fail "Herdr reported an unsafe OMP session path: ${SESSION_FILE:-empty} (shape=${shape:-unreadable})"
    ;;
esac
[ -f "$SESSION_FILE" ] && [ ! -L "$SESSION_FILE" ] || fail "native OMP session path is not a regular file"
OFFSET=$(wc -c < "$SESSION_FILE" | tr -d '[:space:]')

verdict=$(PATH="$WRAPPER_BIN:$BASE_PATH" HERDR_SESSION="$SESSION" \
  FM_BACKEND_HERDR_OMP_EVENT_CONFIRM_SLEEP=10 \
  bash -c '. "$0/bin/backends/herdr.sh"; fm_backend_herdr_send_text_submit "$1" /exit 1 0.2 0 "" omp' \
    "$ROOT" "$TARGET")
[ "$verdict" = empty ] || fail "production OMP Herdr /exit was not acknowledged (verdict=$verdict)"
awk -v session="$SESSION" '$(NF - 1) == "--session" && $NF == session { found = 1 } END { exit !found }' "$WRAPPER_LOG" \
  || fail "the production Herdr route did not carry explicit session binding through the wrapper"

start=$((OFFSET + 1))
tail -c "+$start" "$SESSION_FILE" \
  | jq -se 'any(.[]; .type == "custom" and .customType == "session_exit" and .data.reason == "dispose" and .data.kind == "normal")' \
  >/dev/null 2>&1 || fail "no post-offset normal OMP session_exit event was recorded"

pane_after=$(PATH="$BASE_PATH" "$HERDR_LAB_HELPER" run "$SESSION" pane get "$PANE" 2>&1 || true)
printf '%s' "$pane_after" | jq -e '.error.code == "pane_not_found"' >/dev/null 2>&1 \
  || fail "the exact Herdr pane remained after event-confirmed OMP /exit"

PATH="$BASE_PATH" "$HERDR_LAB_HELPER" teardown "$SESSION" >/dev/null \
  || fail "guarded Herdr teardown or default-session tripwire failed"
TEARDOWN_DONE=1

remaining=$(PATH="$BASE_PATH" "$HERDR_LAB_HELPER" run "fm-lab-inspect-omp-exit-$$" session list --json 2>/dev/null \
  | jq -r --arg s "$SESSION" '.sessions[]? | select(.name == $s) | .name' 2>/dev/null)
[ -z "$remaining" ] || fail "guarded teardown left the OMP lab session behind"

pass "real Herdr OMP /exit: exact native identity, post-offset normal session_exit, pane absence, and guarded tripwire teardown"
